version: "3.4"

services:
  myapp:
    image: "traefik/whoami"
    networks:
      - traefik-network
    environment:
      - TZ=Asia/Jakarta
    deploy:
      # mode: global
      mode: replicated
      replicas: 3
      # update_config:
      #   parallelism: 0
      #   order: start-first
      #   failure_action: rollback
      #   delay: 40s
      labels:
        - "traefik.enable=true"
        # myapp is your service name like above
        - "traefik.http.routers.myapp.rule=Host(`myapp.domain.com`)"
        - "traefik.http.routers.myapp.entrypoints=websecure"
        - "traefik.http.routers.myapp.tls=true"
        - "traefik.http.routers.myapp.tls.options=intermediate@file"
        - "traefik.http.routers.myapp.tls.certresolver=le"
        # change Port of your app (3000=JS, 80=PHP/HTML)
        - "traefik.http.services.myapp.loadbalancer.server.port=80"
        - "traefik.http.services.myapp.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.myapp.loadbalancer.sticky.cookie.httpOnly=true"
        - "traefik.http.services.myapp.loadbalancer.sticky.cookie.name=mydomain"
        - "traefik.http.services.myapp.loadbalancer.sticky.cookie.secure=true"
        - "traefik.http.routers.myapp.middlewares=default-middlewares@file"

networks:
  traefik-network:
    external: true
