services:
  whoami:
    image: traefik/whoami:latest
    deploy:
      # mode: global
      mode: replicated
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`127.0.0.1`)" # change IP/domain
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
