version: '3.4'

services:
  myapp:
    image: randyproxz/nodejs
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.myapp-http.rule=Host(`myapp.domain.com`) 
        - traefik.http.routers.myapp-http.entrypoints=http
        - traefik.http.routers.myapp-http.middlewares=https-redirect
        - traefik.http.routers.myapp-https.rule=Host(`myapp.domain.com`) 
        - traefik.http.routers.myapp-https.entrypoints=https
        - traefik.http.routers.myapp-https.tls=true
        - traefik.http.routers.myapp-https.tls.certresolver=le
        - traefik.http.services.myapp.loadbalancer.server.port=3000
      restart: unless-stopped

networks:
  traefik-public:
    external: true
