version: "3.4"

services:
  web:
    image: randyproxz/nodejs
    networks:
      - traefik-public
    environment:
      - TZ=Asia/Jakarta
    deploy:
      mode: replicated
      replicas: 3
      rollback_config:
        parallelism: 0
        order: stop-first
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
        delay: 40s
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.frontend.rule=Host:myapp.domain.com
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s

networks:
  traefik-public:
    external: true
