version: "3.3"

services:
  traefik:
    image: traefik:v3
    environment:
      - TZ=Asia/jakarta
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/var/log/traefik
      - ./certificates:/certificates
      - ./traefik.yaml:/etc/traefik/traefik.yaml # static traefik configuration
      - ./config:/etc/traefik/config # dynamic traefik configuration
    deploy:
      # mode: global
      mode: replicated
      replicas: 1
      placement:
        # Deploy traefik to node manager only!
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.lbswarm=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.api.rule=Host(`127.0.0.1`)" # change IP/domain
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.middlewares=auth-traefik"
      - "traefik.http.middlewares.auth-traefik.basicauth.users=admin:$$2y$$05$$hhTxWvk54ohYF4ElaOcibOeb6qU9IH5vBZrLl73UUqDg3KUAwXWmi" # admin:traefikdash
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
