# build
FROM node:alpine as build

WORKDIR /app

COPY react .
RUN yarn
RUN yarn build

# nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

RUN mkdir -p /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/
COPY nginx/conf.d/react.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]