version: "3.4"

services:
  react:
    image: randyproxz/react
    restart: unless-stopped
    networks:
      - traefik-public
    environment:
      - TZ=Asia/Jakarta
    deploy:
      mode: global
      # mode: replicated
      # replicas: 3
      rollback_config:
        parallelism: 0
        order: stop-first
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
        delay: 40s
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.rule=Host:react.domain.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-public:
    external: true