version: "3.3"

services:
  traefik:
    image: traefik:v2.9
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - traefik-certificates:/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/traefik:/var/log/traefik
      - ./provider:/provider
      - ./traefik.yml:/etc/traefik/traefik.yml
    command:
      - --configFile=/etc/traefik/traefik.yml # Load all configuration from traefik.yml
    deploy:
      # mode: global
      mode: replicated
      replicas: 1
      placement:
        # Deploy traefik to node manager only!
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.docker.network=traefik-network"
        - "traefik.http.routers.api.service=api@internal"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.routers.api.rule=Host(`IP_ADDRESS_SET`)" # <- Change with your IP Address
        - "traefik.http.services.api.loadbalancer.server.port=8080"
        - "traefik.http.routers.api.middlewares=auth-traefik"
        - "traefik.http.middlewares.auth-traefik.basicauth.users=admin:$$2y$$05$$hhTxWvk54ohYF4ElaOcibOeb6qU9IH5vBZrLl73UUqDg3KUAwXWmi" # admin:traefikdash
    networks:
      - traefik-network

volumes:
  # HTTPS certificates
  traefik-certificates:

networks:
  traefik-network:
    external: true
