version: "3.3"

services:
  traefik:
    image: traefik:v2.9
    ports:
      - 80:80
      - 443:443
      - 9000:9000
      - 8080:8080
    deploy:
      # mode: global
      mode: replicated
      replicas: 1
      placement:
        # Deploy traefik to node manager only!
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-network-certificates:/certificates
      - ./provider:/provider:ro
    command:
      - --providers.docker
      - --providers.docker.network=traefik-network
      - --providers.docker.httpClientTimeout=10m
      - --serversTransport.forwardingTimeouts.idleConnTimeout=10m
      - --serversTransport.forwardingTimeouts.responseHeaderTimeout=10m
      - --serversTransport.forwardingTimeouts.dialTimeout=10m
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode
      - --providers.file.directory=/provider
      # - --providers.file.filename=/etc/traefik/traefik-tls.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=myemail@domain.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --accesslog
      - --log
      - --api
    # configs:
    #   - source: traefik-tls.yml
    #     target: /etc/traefik/traefik-tls.yml
    networks:
      - traefik-network

# configs:
#   traefik-tls.yml:
#     external: true

volumes:
  # HTTPS certificates
  traefik-network-certificates:

networks:
  traefik-network:
    external: true
