version: "3.8"
services:
  wordpress:
    image: 127.0.0.1:5000/wordpress
    deploy:
      placement:
        constraints:
          - node.hostname == srv1
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
        window: 15s
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.rule=Host:your.domain.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
    secrets:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    environment:
      WORDPRESS_DB_HOST: /run/secrets/WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: /run/secrets/WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: /run/secrets/WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: /run/secrets/WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: wp_
      # WORDPRESS_DEBUG: 1
    volumes:
      - /mnt/wp/data:/var/www/html
    networks:
      - traefik-public

#printf "mysql" | docker secret create WORDPRESS_DB_HOST -
#printf "wpusr" | docker secret create WORDPRESS_DB_USER -
#printf "wppassword" | docker secret create WORDPRESS_DB_PASSWORD -
#printf "wpdbname" | docker secret create WORDPRESS_DB_NAME -
secrets:
  WORDPRESS_DB_HOST:
    external: true
  WORDPRESS_DB_USER:
    external: true
  WORDPRESS_DB_PASSWORD:
    external: true
  WORDPRESS_DB_NAME:
    external: true

networks:
  traefik-public:
    external: true