version: "3.8"

services:
  db:
    image: mariadb:10.8.2
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    environment:
      TZ: Asia/Jakarta
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
    # ports:
    #  - 3306:3306
    command: ["mysqld", "--wait_timeout=28800", "--interactive_timeout=28800", "--max_allowed_packet=500M", "--innodb_buffer_pool_size=500M", "--max_connections=10000"]
    volumes:
      - /mnt/mysql/data:/var/lib/mysql
    networks:
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=2G
      - MEMORY_LIMIT=500M
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.rule=Host:pma.<DOMAIN>.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

  mysql-backup:
    image: dsteinkopf/backup-all-mysql:latest
    environment:
      TZ: Asia/Jakarta
      BACKUP_INTERVAL: "86400"
      MYSQL_HOST: mariadb
      MYSQL_USER_FILE: /run/secrets/MYSQL_USER
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    volumes:
      - /mnt/mysql/backup:/var/dbdumps
    networks:
      - traefik-public
    deploy:
      mode: global
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

networks:
  traefik-public:
    external: true

#printf "admin" | docker secret create MYSQL_USER -
#printf "myrootpassword" | docker secret create MYSQL_ROOT_PASSWORD -
#printf "mypassword" | docker secret create MYSQL_PASSWORD -
secrets:
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true
  MYSQL_USER:
    external: true
