version: "3.4"

services:
  php:
    image: randyproxz/php
    restart: unless-stopped
    networks:
      - traefik-public
    environment:
      - TZ=Asia/Jakarta
    # configs:
    # - source: nginx.conf
    #   target: /etc/nginx/conf.d/nginx.conf
    #   mode: 444
    deploy:
      mode: global
      # mode: replicated
      # replicas: 3
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
        delay: 40s
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:php.domain.com
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https

#docker config create nginx.conf nginx.conf
# configs:
#   nginx.conf:
#     external: true
networks:
  traefik-public:
    external: true
