tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - CurveP521
        - CurveP384
        
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        accessControlMaxAge: 100
        addVaryheader: true
        referrerPolicy: origin-when-cross-origin
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    crowdsec-plugin:
      plugin:
        bouncer:
          enabled: true
          logLevel: INFO
          updateIntervalSeconds: 15
          updateMaxFailure: 0
          defaultDecisionSeconds: 15
          httpTimeoutSeconds: 10
          crowdsecMode: stream
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiKey: t7NER5ytJp6PIExEt2dxx28PQiJ5+pu63C2NExjCptc
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
          forwardedHeadersTrustedIPs:
            - 10.0.35.4/32
#            - 172.30.0.0/24
          clientTrustedIPs:
            # Internal LAN IP addresses 
            - 10.20.10.0/24
            - 10.20.15.0/24
            - 10.20.20.0/24
            - 10.20.25.0/24

    modsecurity-plugin:
      plugin:
        traefik-modsecurity-plugin:
          BadRequestsThresholdCount: "25"
          BadRequestsThresholdPeriodSecs: "600"
          JailEnabled: "false"
          JailTimeDurationSecs: "600"
          ModsecurityUrl: http://waf:8080
          TimeoutMillis: "2000"
                    
    secured:
      chain:
        middlewares:
        - default-headers