version: "3.4"

services:
  myapp:
    image: randyproxz/nodejs
    networks:
      - traefik-network
    environment:
      - TZ=Asia/Jakarta
    deploy:
      mode: global
      # mode: replicated
      # replicas: 3
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
        delay: 40s
      labels:
        - "traefik.enable=true"
        # myapp is your service name like above
        - "traefik.http.routers.myapp.rule=Host(`myapp.domain.com`)"
        - "traefik.http.routers.myapp.entrypoints=websecure"
        - "traefik.http.routers.myapp.tls=true"
        - "traefik.http.routers.myapp.tls.options=intermediate@file"
        - "traefik.http.routers.myapp.tls.certresolver=le"
        # change Port of your app (3000=JS, 9000=PHP-FPM, 80=PHP)
        - "traefik.http.services.myapp.loadbalancer.server.port=<your_service_port>"
        - "traefik.http.middlewares.myapp-middlewares.headers.stsincludesubdomains=false"
        - "traefik.http.middlewares.myapp-middlewares.headers.stspreload=true"
        - "traefik.http.middlewares.myapp-middlewares.headers.stsseconds=31536000"
        - "traefik.http.middlewares.myapp-middlewares.headers.isdevelopment=false"
        - "traefik.http.routers.myapp.middlewares=myapp-middlewares"

networks:
  traefik-network:
    external: true
