version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --requirepass <YOUR_PASSWORD>
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    deploy:
      update_config:
        parallelism: 1
        delay: 15s
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  redis:
  redis-config:

# TEST => redis-cli -h 127.0.0.1 -p 6379 -a "<YOUR_PASSWORD>"
# other service to conect to redis using REDIS_HOST "redis" => redis:6379"