[http]
  [http.middlewares]
    [http.middlewares.crowdsec-plugin]
      [http.middlewares.crowdsec-plugin.plugin]
        [http.middlewares.crowdsec-plugin.plugin.crowdsec-bouncer-traefik-plugin]
          Enabled = "true"
          CrowdsecLapiKey = "LAPI_CROWDSEC_BOUNCER_KEY"
          CrowdsecLapiHost = "crowdsec:80"
